title: Ziggy Lee 
logo: "/images/Lucy.jpg" 
description: > 
  <br><br>
  Relevant Links:
  <br><br>
  <a href="https://www.linkedin.com/in/ziggyfloydlee/">LinkedIn</a> 
  <br><br>
  <a href="/portfolio/Zachary%20_Ziggy_%20Lee%20Resume.pdf">Resume</a>
  <br><br>
  <a href="https://github.com/ZiggyFloydLee">GitHub</a>
  
theme: jekyll-theme-minimal
