title: Ziggy Lee # your name (or website title) here
logo: "/images/Lucy.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Relevant Links:
  <br><br>
  <a href="https://www.linkedin.com/in/ziggyfloydlee/">LinkedIn</a> 
  <br><br>
  <a href="/portfolio/Zachary%20_Ziggy_%20Lee%20Resume.pdf">Resume</a>
  <br><br>
  <a href="https://github.com/ZiggyFloydLee">GitHub</a>
  
theme: jekyll-theme-minimal
